lsi: false
safe: true
source: [info]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

title: [Info]
description: [This site gives small info about me]
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
