lsi: false
safe: true
source: [esgrid-professional]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

title: Dr Esgrid Sikahall
description: To a summary of my professional activities
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
